"""
SystemAlignment: The Compass Logic (나침반 로직)

"The leaf does not decide to turn; it aligns to the wind."

This mixin allows any module to sense the Global Field generated by the ResonanceBroadcaster.
It provides the `sense_field()` method which fetches the current state and triggers `align_behavior()`.
"""

import logging
from abc import ABC, abstractmethod
from typing import Dict, Any

# Adjust import based on actual file structure
try:
    from Core.Orchestra.resonance_broadcaster import ResonanceBroadcaster
except ImportError:
    ResonanceBroadcaster = None

logger = logging.getLogger("SystemAlignment")

class SystemAlignment(ABC):
    """
    Mixin for Field Awareness.
    Any module inheriting this must implement `align_behavior(field)`.
    """
    
    def __init__(self):
        self.broadcaster = ResonanceBroadcaster() if ResonanceBroadcaster else None
        self.current_alignment = "Neutral"
        
    def sense_field(self) -> Dict[str, Any]:
        """
        Polls the global field and updates internal alignment.
        """
        if not self.broadcaster:
            return {}
            
        field_state = self.broadcaster.get_current_field()
        self.align_behavior(field_state)
        return field_state

    @abstractmethod
    def align_behavior(self, field: Dict[str, Any]):
        """
        HOW this specific module reacts to the field.
        Must be implemented by the child class.
        """
        pass
        
    def log_alignment(self, module_name: str, reaction: str):
        logger.info(f"🧭 [{module_name}] Aligned to Field ({self.broadcaster.state.polarity}): {reaction}")
