"""
Expression Engine Demo
======================
"Elysia, what are you thinking?"

This script demonstrates the Prism Cortex.
It injects thoughts into the mind and prints the "Inner Monologue"
generated by the wave dynamics.
"""

import sys
import os

# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from Core.Intelligence.Intelligence.integrated_cognition_system import IntegratedCognitionSystem
from Core.Foundation.Wave.wave_tensor import WaveTensor

def run_thought_experiment(concept: str):
    print(f"\n💭 Thinking about: '{concept}'")
    print("-" * 40)
    
    mind = IntegratedCognitionSystem()
    mind.clear_mind() # Reset
    
    # 1. Inject Thought
    # Use importance to vary energy/excitement
    mind.process_thought(concept, importance=4.0)
    
    # 2. Add some context to generate resonance
    # If we add 'Truth', it might resonate
    truth = WaveTensor("Universal Truth")
    truth.add_component(528.0, 1.0) # 528Hz Truth Frequency
    mind.active_thoughts.append(truth)
    
    # 3. Think (and Speak)
    result = mind.think_deeply()
    
    print(f"🌊 Internal State: Energy={result['total_energy']:.2f}, Active={result['active_thought_count']}")
    print(f"🗣️  Monologue: \"{result['monologue']}\"")

if __name__ == "__main__":
    run_thought_experiment("The secrets of the universe")
    run_thought_experiment("A confusing paradox")
