"""
Saga System (The Chronicle of Meaning)
======================================

Records "Concept Trajectories" (stories) generated by the Memetic Engine.
A Saga is not just a log; it is a high-resonance path through the 64D concept space.

"History is a vector field. Myth is a resonant orbit."
"""

import logging
from typing import Dict, List, Optional
from dataclasses import dataclass, field
import time

from Core.Foundation.Mind.memetic_field import MemeticField, Trajectory

@dataclass
class Saga:
    """
    A recorded story/myth with high resonance.
    """
    id: str
    title: str
    trajectory: Trajectory
    author_id: str
    timestamp: float
    resonance: float
    tags: List[str] = field(default_factory=list)

class SagaSystem:
    """
    Manages the recording and archiving of Sagas.
    """
    def __init__(self, memetic_field: MemeticField):
        self.memetic_field = memetic_field
        self.active_trajectories: Dict[str, List[str]] = {} # agent_id -> list of concept_ids
        self.sagas: List[Saga] = []
        self.logger = logging.getLogger(__name__)

    def start_trajectory(self, agent_id: str):
        """Begin tracking a new thought/action sequence."""
        self.active_trajectories[agent_id] = []

    def add_step(self, agent_id: str, concept_id: str):
        """Add a concept to the agent's current trajectory."""
        if agent_id not in self.active_trajectories:
            self.start_trajectory(agent_id)
        
        self.active_trajectories[agent_id].append(concept_id)
        
        # Auto-evaluate if trajectory gets too long
        if len(self.active_trajectories[agent_id]) > 10:
            self.commit_trajectory(agent_id)

    def commit_trajectory(self, agent_id: str) -> Optional[Saga]:
        """
        Evaluate and potentially archive the current trajectory.
        Returns the Saga if it was resonant enough to be recorded.
        """
        if agent_id not in self.active_trajectories:
            return None
            
        path = self.active_trajectories.pop(agent_id)
        if len(path) < 3:
            return None # Too short to be a story

        # Evaluate trajectory in Memetic Field
        trajectory = self.memetic_field.form_trajectory(path)
        
        # Thresholds for "Myth-worthiness"
        # Resonance > 0.7 means strong constructive interference (truth)
        # Coherence > 0.5 means it makes grammatical/topological sense
        if trajectory.resonance > 0.7 and trajectory.coherence > 0.5:
            saga = Saga(
                id=f"saga_{int(time.time())}_{agent_id}",
                title=f"The Path of {path[0]} to {path[-1]}",
                trajectory=trajectory,
                author_id=agent_id,
                timestamp=time.time(),
                resonance=trajectory.resonance,
                tags=path
            )
            self.sagas.append(saga)
            self.logger.info(f"📜 New Saga Recorded: '{saga.title}' (Res: {saga.resonance:.2f})")
            
            # Reinforce the field!
            self.memetic_field.reinforce(trajectory, intensity=0.2)
            
            return saga
            
        return None

    def get_top_sagas(self, limit: int = 5) -> List[Saga]:
        """Return the most resonant sagas."""
        return sorted(self.sagas, key=lambda s: s.resonance, reverse=True)[:limit]
