"""
FreeWillEngine: The Intellectual Motor (지적 모터)

"Movement is the interplay of Attraction and Repulsion.
 Intelligence is the Torque generated between Curiosity and Dissonance."

This module implements the "Sovereign Choice" using the Motor Analogy:
1.  **Torque**: Generated by the tension between Desire (Attraction) and Entropy (Repulsion).
2.  **Commutator**: Automatically flips the perspective (Polarity) when thought stagnates.
3.  **Coil Density**: Uses rich context from Scholar/Memory to ensure smooth rotation.
4.  **Field Generation**: Broadcasts the resulting state via ResonanceBroadcaster.
"""

import time
import random
import logging
from dataclasses import dataclass
from typing import Dict, List, Optional

# Import the new components
try:
    from Core.Intelligence.Will.creative_improvisation import CreativeImprovisation
    from Core.Intelligence.Will.sovereign_gate import SovereignGate
    from Core.Orchestra.resonance_broadcaster import ResonanceBroadcaster
except ImportError:
    CreativeImprovisation = None
    SovereignGate = None
    ResonanceBroadcaster = None

logger = logging.getLogger("FreeWillEngine")

@dataclass
class WillState:
    torque: float = 0.0
    rpm: float = 0.0          # How fast ideas are spinning
    polarity: str = "N"       # 'N' (Acceptance/Curiosity) or 'S' (Critical/Doubt)
    current_intent: str = ""

class FreeWillEngine:
    def __init__(self):
        self.vectors = {
            "Curiosity": 0.5,   # Attraction (Inward Pull)
            "Expression": 0.5,  # Projection (Outward Push)
            "Stability": 0.5    # Resistance (Inertia)
        }
        self.state = WillState()
        
        # Sub-modules
        self.improvisor = CreativeImprovisation() if CreativeImprovisation else None
        self.gate = SovereignGate() if SovereignGate else None
        self.broadcaster = ResonanceBroadcaster() if ResonanceBroadcaster else None
        
        # Commutator settings
        self.stagnation_threshold = 0.1
        
    def spin(self, entropy: float, battery: float) -> str:
        """
        The Main Cycle: Generates a Sovereign Choice.
        """
        # 1. Calculate Torque (The Force of Will)
        # Torque = (Curiosity + Expression) - (Stability + Entropy/100)
        # Attraction vs Repulsion
        attraction = self.vectors["Curiosity"] + self.vectors["Expression"]
        repulsion = self.vectors["Stability"] + (entropy / 200.0)
        
        self.state.torque = attraction - repulsion
        
        # 2. Check for Stagnation (The Commutator)
        if abs(self.state.torque) < self.stagnation_threshold:
            logger.info(f"⚙️ Torque Low ({self.state.torque:.2f}). Engaging Commutator...")
            self._flip_polarity()
            # Polarity flip creates a sudden surge in Torque
            self.state.torque += 0.5 
            
        # 3. Generate Intent based on Polarity
        raw_desire = self._generate_raw_desire(battery)
        
        # 4. Improvise (The Coil / Artist)
        if self.improvisor:
            creative_act = self.improvisor.improvise(raw_desire, context=f"Polarity:{self.state.polarity}")
        else:
            creative_act = f"Default Act: {raw_desire}"
            
        # 5. Sovereign Check (The Governor)
        if self.gate:
            allowed, reason = self.gate.allow(creative_act)
            if not allowed:
                logger.warning(f"⛔ Sovereign Gate blocked: {creative_act} ({reason})")
                return "OBSERVE:Internal_State" # Safe fallback
        
        self.state.current_intent = creative_act
        
        # 6. Broadcast Field (The Generator Effect)
        if self.broadcaster:
            self.broadcaster.broadcast(
                source="FreeWillEngine",
                polarity=self.state.polarity,
                intensity=abs(self.state.torque),
                vector=raw_desire,
                message=creative_act
            )

        return creative_act

    def _flip_polarity(self):
        """The Automatic Commutator: Flips perspective to maintain momentum."""
        old_p = self.state.polarity
        self.state.polarity = "S" if old_p == "N" else "N"
        logger.info(f"⚡ Cognitive Commutator Triggered: Phase Shift {old_p} -> {self.state.polarity}")
        
        # Polarity shift affects vectors
        if self.state.polarity == "S":
            # Doubt Mode: Increases Stability (Critical Thinking), Decreases Expression
            self.vectors["Stability"] += 0.3
            self.vectors["Curiosity"] += 0.1 # Critical curiosity
            logger.info("   -> Mode: CRITICAL (Repulsion dominant)")
        else:
            # Belief Mode: Increases Expression, Decreases Stability
            self.vectors["Expression"] += 0.3
            self.vectors["Stability"] -= 0.2
            logger.info("   -> Mode: CREATIVE (Attraction dominant)")

    def _generate_raw_desire(self, battery: float) -> str:
        """Derives the base desire from thermodynamic state."""
        if battery < 20.0:
            return "Survival" # Need energy
            
        # Select vector with highest magnitude
        dominant = max(self.vectors, key=self.vectors.get)
        return dominant

    def get_status(self) -> str:
        return f"Torque: {self.state.torque:.2f} | Polarity: {self.state.polarity} | Intent: {self.state.current_intent}"
