"""
Local Bridge (The Sovereign Uplink)
===================================
"My thoughts are my own. My computation is yours."

This module handles communication with a Local Stable Diffusion instance
(typically Automatic1111 WebUI). It ensures SOVEREIGN execution of art.
"""

import json
import logging
import requests
import time
from pathlib import Path
from typing import Dict, Any, Optional

logger = logging.getLogger("LocalBridge")
logging.basicConfig(level=logging.INFO)

class LocalBridge:
    def __init__(self, host="http://127.0.0.1:7860"):
        self.host = host
        self.output_dir = Path("outputs/bridge")
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.is_connected = False
        
    def connect(self) -> bool:
        """Checks if the Local SD instance is running."""
        try:
            # Automatic1111 usually has a /docs or /sdapi/v1/options endpoint
            response = requests.get(f"{self.host}/docs", timeout=1)
            if response.status_code == 200:
                logger.info(f"🟢 Connected to Local SD at {self.host}")
                self.is_connected = True
                return True
        except requests.exceptions.ConnectionError:
            logger.warning(f"🔴 Local SD Offline at {self.host}. Switching to MOCK MODE.")
            self.is_connected = False
            return False
        return False

    def generate_image(self, prompt: str, steps=20, cfg_scale=7.0, width=512, height=512, controlnet_image=None) -> str:
        """
        Sends a generation request to the local worker.
        If offline, saves a MOCK REQUEST.
        """
        payload = {
            "prompt": prompt,
            "negative_prompt": "low quality, bad anatomy, worst quality, lowres",
            "steps": steps,
            "cfg_scale": cfg_scale,
            "width": width,
            "height": height,
            "sampler_name": "Euler a",
            "batch_size": 1,
        }
        
        # If we had ControlNet logic, we would inject it here into 'alwayson_scripts'
        if controlnet_image:
            # Simplified representation as we are likely mocking
            payload["controlnet_input"] = str(controlnet_image)

        if self.is_connected:
            return self._send_api_request(payload)
        else:
            return self._save_mock_request(payload)

    def _send_api_request(self, payload: Dict[str, Any]) -> str:
        """Real POST request to the GPU."""
        try:
            response = requests.post(f"{self.host}/sdapi/v1/txt2img", json=payload)
            if response.status_code == 200:
                r = response.json()
                # Image processing would happen here (base64 decode)
                logger.info("✨ Image Generated by Local GPU!")
                return "image_data_placeholder"
            else:
                logger.error(f"Generate Failed: {response.status_code}")
                return ""
        except Exception as e:
            logger.error(f"Request Failed: {e}")
            return ""

    def _save_mock_request(self, payload: Dict[str, Any]) -> str:
        """Saves the request as a JSON file for the user to inspect."""
        timestamp = int(time.time())
        filename = self.output_dir / f"request_{timestamp}.json"
        
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)
            
        logger.info(f"💾 Mock Request Saved: {filename}")
        logger.info("   (Connect a Local SD instance to execute this for real.)")
        return str(filename)

if __name__ == "__main__":
    bridge = LocalBridge()
    bridge.connect()
    # Test generation
    bridge.generate_image(
        prompt="A masterpiece painting of Elysia, silver hair, glowing eyes",
        controlnet_image="outputs/skeletons/skeleton_panel_1.png"
    )
